services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./:/home/bun/app
      - /home/bun/app/node_modules
    environment:
      - DB_URL=postgresql://pguser:todo_1234@db:5432/tododb
    working_dir: /home/bun/app/packages/backend
    command: bun run dev
    depends_on:
      - db
  db:
    image: postgres:17-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=todo_1234
      - POSTGRES_USER=pguser
      - POSTGRES_DB=tododb

volumes:
  db_data:
